/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CartManager;
import Controller.OrderHistoryController;
import Controller.UserSession;
import Model.Aluno;
import Model.CartItem;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author unifvipereira
 */
public class CartScreen extends javax.swing.JFrame {

    /**
     * Creates new form CartScreen
     */
    public CartScreen() {
        initComponents();
        loadCart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstCart = new javax.swing.JList<>();
        lblTotal = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnFinalize = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(lstCart);

        lblTotal.setText("Total: R$ 0,00");
        lblSubtotal.setText("Subtotal: R$ 0,00");
        lblTax.setText("Taxa (5%): R$ 0,00");

        btnClose.setText("Fechar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Carrinho");

        btnFinalize.setText("Finalizar Pedido");
        btnFinalize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizeActionPerformed(evt);
            }
        });

        btnClear.setText("Limpar Carrinho");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal)
                            .addComponent(lblSubtotal)
                            .addComponent(lblTax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(btnClose)
                    .addComponent(btnFinalize)
                    .addComponent(btnClear))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.dispose();
    }                                        

    private void btnFinalizeActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // Here you would normally save the order to the database
        // For now, just show a message and open the order history
        JOptionPane.showMessageDialog(this, "Pedido finalizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        CartManager.getInstance().clearCart();
        OrderHistory orderHistory = new OrderHistory();
        new OrderHistoryController(orderHistory, UserSession.getInstance().getLoggedInAluno().getId());
        orderHistory.setVisible(true);
        this.dispose();
    }                                           

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        CartManager.getInstance().clearCart();
        loadCart();
        JOptionPane.showMessageDialog(this, "Carrinho esvaziado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }                                        

    private void loadCart() {
        List<CartItem> items = CartManager.getInstance().getCartItems();
        DefaultListModel<String> model = new DefaultListModel<>();
        for (CartItem item : items) {
            model.addElement(item.getFood().getName() + " - Quantidade: " + item.getQuantity());
        }
        lstCart.setModel(model);
        updateTotal();
    }

    private void updateTotal() {
        double subtotal = 0;
        for (CartItem item : CartManager.getInstance().getCartItems()) {
            subtotal += item.getTotalPrice();
        }
        double tax = CartManager.getInstance().getTax();
        double total = subtotal + tax;
        
        lblSubtotal.setText("Subtotal: R$ " + String.format("%.2f", subtotal));
        lblTax.setText("Taxa (5%): R$ " + String.format("%.2f", tax));
        lblTotal.setText("Total: R$ " + String.format("%.2f", total));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnFinalize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTax;
    private javax.swing.JList<String> lstCart;
    // End of variables declaration                   
}
